services:
    Plenta\ContaoTestimonialsBundle\EventListener\Contao\Dca\TlTestimonialsListener:
        public: true

    Plenta\ContaoTestimonialsBundle\EventListener\DataContainer\PaletteManipulatorCallback:
        public: true
        arguments:
            - '@request_stack'
