services:
    plenta.contao_testimonials_bundle.helper.testimonial:
        class: Plenta\ContaoTestimonialsBundle\Helper\Testimonial
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'

    Plenta\ContaoTestimonialsBundle\Controller\ContentElement\TestimonialContentElementController:
        arguments:
            - '@plenta.contao_testimonials_bundle.helper.testimonial'
        tags:
            -   name: contao.content_element
                category: texts
                template: ce_plenta_testimonial
                renderer: forward
                type: !php/const Plenta\ContaoTestimonialsBundle\Controller\ContentElement\TestimonialContentElementController::TYPE

    Plenta\ContaoTestimonialsBundle\Controller\FrontendModule\TestimonialFrontendModuleController:
        arguments:
            - '@plenta.contao_testimonials_bundle.helper.testimonial'
        tags:
            -   name: contao.frontend_module
                category: miscellaneous
                type: !php/const Plenta\ContaoTestimonialsBundle\Controller\FrontendModule\TestimonialFrontendModuleController::TYPE

    Plenta\ContaoTestimonialsBundle\Migration\ContentTypeMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
