services:
    Plenta\ContaoTestimonialsBundle\Controller\ContentElement\TestimonialContentElementController:
        arguments:
            - '@database_connection'
        tags:
            -   name: contao.content_element
                category: texts
                template: ce_testimonial
                renderer: forward

    Plenta\ContaoTestimonialsBundle\Controller\FrontendModule\TestimonialFrontendModuleController:
        tags:
            -   name: contao.frontend_module
                category: miscellaneous
                type: !php/const Plenta\ContaoTestimonialsBundle\Controller\FrontendModule\TestimonialFrontendModuleController::TYPE
